CREATE TRIGGER SADD_MILHAS
AFTER INSERT ON CLIENTE_VOO
FOR EACH ROW UPDATE MILHAS
SET QUANTIDADE= QUANTIDADE + 
(SELECT DISTANCIA FROM VOO
, CLIENTE_VOO 
 WHERE NEW.VOO = VOO.CODIGO)/10
 WHERE CLIENTE  = NEW.CLIENTE;