CREATE SEQUENCE SEQUENCIA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQUENCIA2 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQUENCIA3 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQUENCIA4 START WITH 1 INCREMENT BY 1;


CREATE TABLE CLIENTE(
	CODIGO INT DEFAULT (NEXT VALUE FOR SEQUENCIA),
	NOME VARCHAR(60),
	ENDERECO VARCHAR(60),
	PRIMARY KEY(CODIGO)
);

CREATE TABLE PILOTO(
	CODIGO INT DEFAULT (NEXT VALUE FOR SEQUENCIA2),
	NOME VARCHAR(60),
	NUM_VOOS INT,
	PRIMARY KEY(CODIGO)
);

CREATE TABLE VOO(
	CODIGO INT DEFAULT (NEXT VALUE FOR SEQUENCIA3),
	PILOTO INT,
	TIPO VARCHAR (60),
	NUM_PASSAGEIROS INT DEFAULT 0,
	DISTANCIA INT DEFAULT 0,
	PRIMARY KEY(CODIGO),
	FOREIGN KEY(PILOTO) REFERENCES PILOTO(CODIGO)
);

CREATE TABLE MILHAS(
	CODIGO INT DEFAULT (NEXT VALUE FOR SEQUENCIA4),
	CLIENTE INT DEFAULT 0,
	QUANTIDADE INT DEFAULT 0,
	PRIMARY KEY(CODIGO),
	FOREIGN KEY(CLIENTE) REFERENCES CLIENTE(CODIGO)
);

CREATE TABLE CLIENTE_VOO(
	CLIENTE INT DEFAULT 0,
	VOO INT DEFAULT 0,
	CLASSE VARCHAR(60),
	PRIMARY KEY(CLIENTE,VOO),
	FOREIGN KEY(CLIENTE) REFERENCES CLIENTE(CODIGO),
	FOREIGN KEY(VOO) REFERENCES VOO(CODIGO)
);